/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CaseId = bigint;
export type CaseStatus = { 'closed' : null } |
  { 'open' : null } |
  { 'under_investigation' : null } |
  { 'chargeshed' : null };
export interface CaseView {
  'id' : CaseId,
  'status' : CaseStatus,
  'title' : string,
  'caseNumber' : string,
  'createdBy' : UserId,
  'createdDate' : Timestamp,
  'firIds' : Array<FirId>,
}
export interface CreateCaseInput { 'title' : string, 'caseNumber' : string }
export interface CreateFirInput {
  'offenseType' : OffenseType,
  'complainantName' : string,
  'document' : ExternalBlob,
  'caseId' : [] | [CaseId],
  'firNumber' : string,
  'documentFilename' : string,
  'caseTitle' : string,
  'dateOfIncident' : Timestamp,
}
export type ExternalBlob = Uint8Array;
export interface FirFilter {
  'status' : [] | [FirStatus],
  'toDate' : [] | [Timestamp],
  'fromDate' : [] | [Timestamp],
  'caseId' : [] | [CaseId],
}
export type FirId = bigint;
export interface FirRecordView {
  'id' : FirId,
  'status' : FirStatus,
  'offenseType' : OffenseType,
  'complainantName' : string,
  'document' : ExternalBlob,
  'caseId' : [] | [CaseId],
  'firNumber' : string,
  'uploadDate' : Timestamp,
  'documentFilename' : string,
  'caseTitle' : string,
  'uploadedBy' : UserId,
  'dateOfIncident' : Timestamp,
}
export type FirStatus = { 'summarizing' : null } |
  { 'summary_ready' : null } |
  { 'summary_failed' : null } |
  { 'pending_summary' : null };
export interface LinkFirInput { 'firId' : FirId, 'caseId' : CaseId }
export type OffenseType = string;
export interface SaveSummaryInput { 'firId' : FirId, 'summaryText' : string }
export type SummaryId = bigint;
export interface SummaryView {
  'id' : SummaryId,
  'firId' : FirId,
  'lastEditedDate' : [] | [Timestamp],
  'summaryText' : string,
  'lastEditedBy' : [] | [UserId],
  'generatedDate' : Timestamp,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpdateCaseInput {
  'id' : CaseId,
  'status' : [] | [CaseStatus],
  'title' : [] | [string],
  'caseNumber' : [] | [string],
}
export interface UpdateFirStatusInput { 'id' : FirId, 'status' : FirStatus }
export interface UpdateSummaryInput { 'id' : SummaryId, 'summaryText' : string }
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCase' : ActorMethod<[CreateCaseInput], CaseView>,
  'createFir' : ActorMethod<[CreateFirInput], FirRecordView>,
  'deleteFir' : ActorMethod<[FirId], boolean>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCase' : ActorMethod<[CaseId], [] | [CaseView]>,
  'getFir' : ActorMethod<[FirId], [] | [FirRecordView]>,
  'getSummary' : ActorMethod<[SummaryId], [] | [SummaryView]>,
  'getSummaryByFirId' : ActorMethod<[FirId], [] | [SummaryView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'linkFirToCase' : ActorMethod<[LinkFirInput], boolean>,
  'listCases' : ActorMethod<[], Array<CaseView>>,
  'listFirs' : ActorMethod<[], Array<FirRecordView>>,
  'listFirsFiltered' : ActorMethod<[FirFilter], Array<FirRecordView>>,
  'listSummaries' : ActorMethod<[], Array<SummaryView>>,
  'saveSummary' : ActorMethod<[SaveSummaryInput], SummaryView>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'triggerFirSummarization' : ActorMethod<[FirId], string>,
  'updateCase' : ActorMethod<[UpdateCaseInput], boolean>,
  'updateFirStatus' : ActorMethod<[UpdateFirStatusInput], boolean>,
  'updateSummary' : ActorMethod<[UpdateSummaryInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];