/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreateCaseInput = IDL.Record({
  'title' : IDL.Text,
  'caseNumber' : IDL.Text,
});
export const CaseId = IDL.Nat;
export const CaseStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'under_investigation' : IDL.Null,
  'chargeshed' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const FirId = IDL.Nat;
export const CaseView = IDL.Record({
  'id' : CaseId,
  'status' : CaseStatus,
  'title' : IDL.Text,
  'caseNumber' : IDL.Text,
  'createdBy' : UserId,
  'createdDate' : Timestamp,
  'firIds' : IDL.Vec(FirId),
});
export const OffenseType = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CreateFirInput = IDL.Record({
  'offenseType' : OffenseType,
  'complainantName' : IDL.Text,
  'document' : ExternalBlob,
  'caseId' : IDL.Opt(CaseId),
  'firNumber' : IDL.Text,
  'documentFilename' : IDL.Text,
  'caseTitle' : IDL.Text,
  'dateOfIncident' : Timestamp,
});
export const FirStatus = IDL.Variant({
  'summarizing' : IDL.Null,
  'summary_ready' : IDL.Null,
  'summary_failed' : IDL.Null,
  'pending_summary' : IDL.Null,
});
export const FirRecordView = IDL.Record({
  'id' : FirId,
  'status' : FirStatus,
  'offenseType' : OffenseType,
  'complainantName' : IDL.Text,
  'document' : ExternalBlob,
  'caseId' : IDL.Opt(CaseId),
  'firNumber' : IDL.Text,
  'uploadDate' : Timestamp,
  'documentFilename' : IDL.Text,
  'caseTitle' : IDL.Text,
  'uploadedBy' : UserId,
  'dateOfIncident' : Timestamp,
});
export const SummaryId = IDL.Nat;
export const SummaryView = IDL.Record({
  'id' : SummaryId,
  'firId' : FirId,
  'lastEditedDate' : IDL.Opt(Timestamp),
  'summaryText' : IDL.Text,
  'lastEditedBy' : IDL.Opt(UserId),
  'generatedDate' : Timestamp,
});
export const LinkFirInput = IDL.Record({ 'firId' : FirId, 'caseId' : CaseId });
export const FirFilter = IDL.Record({
  'status' : IDL.Opt(FirStatus),
  'toDate' : IDL.Opt(Timestamp),
  'fromDate' : IDL.Opt(Timestamp),
  'caseId' : IDL.Opt(CaseId),
});
export const SaveSummaryInput = IDL.Record({
  'firId' : FirId,
  'summaryText' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdateCaseInput = IDL.Record({
  'id' : CaseId,
  'status' : IDL.Opt(CaseStatus),
  'title' : IDL.Opt(IDL.Text),
  'caseNumber' : IDL.Opt(IDL.Text),
});
export const UpdateFirStatusInput = IDL.Record({
  'id' : FirId,
  'status' : FirStatus,
});
export const UpdateSummaryInput = IDL.Record({
  'id' : SummaryId,
  'summaryText' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCase' : IDL.Func([CreateCaseInput], [CaseView], []),
  'createFir' : IDL.Func([CreateFirInput], [FirRecordView], []),
  'deleteFir' : IDL.Func([FirId], [IDL.Bool], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCase' : IDL.Func([CaseId], [IDL.Opt(CaseView)], ['query']),
  'getFir' : IDL.Func([FirId], [IDL.Opt(FirRecordView)], ['query']),
  'getSummary' : IDL.Func([SummaryId], [IDL.Opt(SummaryView)], ['query']),
  'getSummaryByFirId' : IDL.Func([FirId], [IDL.Opt(SummaryView)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'linkFirToCase' : IDL.Func([LinkFirInput], [IDL.Bool], []),
  'listCases' : IDL.Func([], [IDL.Vec(CaseView)], ['query']),
  'listFirs' : IDL.Func([], [IDL.Vec(FirRecordView)], ['query']),
  'listFirsFiltered' : IDL.Func(
      [FirFilter],
      [IDL.Vec(FirRecordView)],
      ['query'],
    ),
  'listSummaries' : IDL.Func([], [IDL.Vec(SummaryView)], ['query']),
  'saveSummary' : IDL.Func([SaveSummaryInput], [SummaryView], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'triggerFirSummarization' : IDL.Func([FirId], [IDL.Text], []),
  'updateCase' : IDL.Func([UpdateCaseInput], [IDL.Bool], []),
  'updateFirStatus' : IDL.Func([UpdateFirStatusInput], [IDL.Bool], []),
  'updateSummary' : IDL.Func([UpdateSummaryInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreateCaseInput = IDL.Record({
    'title' : IDL.Text,
    'caseNumber' : IDL.Text,
  });
  const CaseId = IDL.Nat;
  const CaseStatus = IDL.Variant({
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'under_investigation' : IDL.Null,
    'chargeshed' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const FirId = IDL.Nat;
  const CaseView = IDL.Record({
    'id' : CaseId,
    'status' : CaseStatus,
    'title' : IDL.Text,
    'caseNumber' : IDL.Text,
    'createdBy' : UserId,
    'createdDate' : Timestamp,
    'firIds' : IDL.Vec(FirId),
  });
  const OffenseType = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CreateFirInput = IDL.Record({
    'offenseType' : OffenseType,
    'complainantName' : IDL.Text,
    'document' : ExternalBlob,
    'caseId' : IDL.Opt(CaseId),
    'firNumber' : IDL.Text,
    'documentFilename' : IDL.Text,
    'caseTitle' : IDL.Text,
    'dateOfIncident' : Timestamp,
  });
  const FirStatus = IDL.Variant({
    'summarizing' : IDL.Null,
    'summary_ready' : IDL.Null,
    'summary_failed' : IDL.Null,
    'pending_summary' : IDL.Null,
  });
  const FirRecordView = IDL.Record({
    'id' : FirId,
    'status' : FirStatus,
    'offenseType' : OffenseType,
    'complainantName' : IDL.Text,
    'document' : ExternalBlob,
    'caseId' : IDL.Opt(CaseId),
    'firNumber' : IDL.Text,
    'uploadDate' : Timestamp,
    'documentFilename' : IDL.Text,
    'caseTitle' : IDL.Text,
    'uploadedBy' : UserId,
    'dateOfIncident' : Timestamp,
  });
  const SummaryId = IDL.Nat;
  const SummaryView = IDL.Record({
    'id' : SummaryId,
    'firId' : FirId,
    'lastEditedDate' : IDL.Opt(Timestamp),
    'summaryText' : IDL.Text,
    'lastEditedBy' : IDL.Opt(UserId),
    'generatedDate' : Timestamp,
  });
  const LinkFirInput = IDL.Record({ 'firId' : FirId, 'caseId' : CaseId });
  const FirFilter = IDL.Record({
    'status' : IDL.Opt(FirStatus),
    'toDate' : IDL.Opt(Timestamp),
    'fromDate' : IDL.Opt(Timestamp),
    'caseId' : IDL.Opt(CaseId),
  });
  const SaveSummaryInput = IDL.Record({
    'firId' : FirId,
    'summaryText' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdateCaseInput = IDL.Record({
    'id' : CaseId,
    'status' : IDL.Opt(CaseStatus),
    'title' : IDL.Opt(IDL.Text),
    'caseNumber' : IDL.Opt(IDL.Text),
  });
  const UpdateFirStatusInput = IDL.Record({
    'id' : FirId,
    'status' : FirStatus,
  });
  const UpdateSummaryInput = IDL.Record({
    'id' : SummaryId,
    'summaryText' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCase' : IDL.Func([CreateCaseInput], [CaseView], []),
    'createFir' : IDL.Func([CreateFirInput], [FirRecordView], []),
    'deleteFir' : IDL.Func([FirId], [IDL.Bool], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCase' : IDL.Func([CaseId], [IDL.Opt(CaseView)], ['query']),
    'getFir' : IDL.Func([FirId], [IDL.Opt(FirRecordView)], ['query']),
    'getSummary' : IDL.Func([SummaryId], [IDL.Opt(SummaryView)], ['query']),
    'getSummaryByFirId' : IDL.Func([FirId], [IDL.Opt(SummaryView)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'linkFirToCase' : IDL.Func([LinkFirInput], [IDL.Bool], []),
    'listCases' : IDL.Func([], [IDL.Vec(CaseView)], ['query']),
    'listFirs' : IDL.Func([], [IDL.Vec(FirRecordView)], ['query']),
    'listFirsFiltered' : IDL.Func(
        [FirFilter],
        [IDL.Vec(FirRecordView)],
        ['query'],
      ),
    'listSummaries' : IDL.Func([], [IDL.Vec(SummaryView)], ['query']),
    'saveSummary' : IDL.Func([SaveSummaryInput], [SummaryView], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'triggerFirSummarization' : IDL.Func([FirId], [IDL.Text], []),
    'updateCase' : IDL.Func([UpdateCaseInput], [IDL.Bool], []),
    'updateFirStatus' : IDL.Func([UpdateFirStatusInput], [IDL.Bool], []),
    'updateSummary' : IDL.Func([UpdateSummaryInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };