/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface CreateCaseInput {
    title: string;
    caseNumber: string;
}
export interface FirRecordView {
    id: FirId;
    status: FirStatus;
    offenseType: OffenseType;
    complainantName: string;
    document: ExternalBlob;
    caseId?: CaseId;
    firNumber: string;
    uploadDate: Timestamp;
    documentFilename: string;
    caseTitle: string;
    uploadedBy: UserId;
    dateOfIncident: Timestamp;
}
export interface UpdateFirStatusInput {
    id: FirId;
    status: FirStatus;
}
export interface SaveSummaryInput {
    firId: FirId;
    summaryText: string;
}
export interface LinkFirInput {
    firId: FirId;
    caseId: CaseId;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type FirId = bigint;
export interface UpdateCaseInput {
    id: CaseId;
    status?: CaseStatus;
    title?: string;
    caseNumber?: string;
}
export type OffenseType = string;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type SummaryId = bigint;
export interface UpdateSummaryInput {
    id: SummaryId;
    summaryText: string;
}
export interface CreateFirInput {
    offenseType: OffenseType;
    complainantName: string;
    document: ExternalBlob;
    caseId?: CaseId;
    firNumber: string;
    documentFilename: string;
    caseTitle: string;
    dateOfIncident: Timestamp;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface CaseView {
    id: CaseId;
    status: CaseStatus;
    title: string;
    caseNumber: string;
    createdBy: UserId;
    createdDate: Timestamp;
    firIds: Array<FirId>;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface SummaryView {
    id: SummaryId;
    firId: FirId;
    lastEditedDate?: Timestamp;
    summaryText: string;
    lastEditedBy?: UserId;
    generatedDate: Timestamp;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type UserId = Principal;
export type CaseId = bigint;
export interface FirFilter {
    status?: FirStatus;
    toDate?: Timestamp;
    fromDate?: Timestamp;
    caseId?: CaseId;
}
export enum CaseStatus {
    closed = "closed",
    open = "open",
    under_investigation = "under_investigation",
    chargeshed = "chargeshed"
}
export enum FirStatus {
    summarizing = "summarizing",
    summary_ready = "summary_ready",
    summary_failed = "summary_failed",
    pending_summary = "pending_summary"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCase(input: CreateCaseInput): Promise<CaseView>;
    createFir(input: CreateFirInput): Promise<FirRecordView>;
    deleteFir(id: FirId): Promise<boolean>;
    getCallerUserRole(): Promise<UserRole>;
    getCase(id: CaseId): Promise<CaseView | null>;
    getFir(id: FirId): Promise<FirRecordView | null>;
    getSummary(id: SummaryId): Promise<SummaryView | null>;
    getSummaryByFirId(firId: FirId): Promise<SummaryView | null>;
    isCallerAdmin(): Promise<boolean>;
    linkFirToCase(input: LinkFirInput): Promise<boolean>;
    listCases(): Promise<Array<CaseView>>;
    listFirs(): Promise<Array<FirRecordView>>;
    listFirsFiltered(filter: FirFilter): Promise<Array<FirRecordView>>;
    listSummaries(): Promise<Array<SummaryView>>;
    saveSummary(input: SaveSummaryInput): Promise<SummaryView>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    triggerFirSummarization(firId: FirId): Promise<string>;
    updateCase(input: UpdateCaseInput): Promise<boolean>;
    updateFirStatus(input: UpdateFirStatusInput): Promise<boolean>;
    updateSummary(input: UpdateSummaryInput): Promise<boolean>;
}
import type { CaseId as _CaseId, CaseStatus as _CaseStatus, CaseView as _CaseView, CreateFirInput as _CreateFirInput, ExternalBlob as _ExternalBlob, FirFilter as _FirFilter, FirId as _FirId, FirRecordView as _FirRecordView, FirStatus as _FirStatus, OffenseType as _OffenseType, SummaryId as _SummaryId, SummaryView as _SummaryView, Timestamp as _Timestamp, UpdateCaseInput as _UpdateCaseInput, UpdateFirStatusInput as _UpdateFirStatusInput, UserId as _UserId, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCase(arg0: CreateCaseInput): Promise<CaseView> {
        if (this.processError) {
            try {
                const result = await this.actor.createCase(arg0);
                return from_candid_CaseView_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCase(arg0);
            return from_candid_CaseView_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createFir(arg0: CreateFirInput): Promise<FirRecordView> {
        if (this.processError) {
            try {
                const result = await this.actor.createFir(await to_candid_CreateFirInput_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_FirRecordView_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFir(await to_candid_CreateFirInput_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_FirRecordView_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteFir(arg0: FirId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFir(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFir(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCase(arg0: CaseId): Promise<CaseView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCase(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCase(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFir(arg0: FirId): Promise<FirRecordView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFir(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFir(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSummary(arg0: SummaryId): Promise<SummaryView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSummary(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSummary(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSummaryByFirId(arg0: FirId): Promise<SummaryView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSummaryByFirId(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSummaryByFirId(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async linkFirToCase(arg0: LinkFirInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.linkFirToCase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.linkFirToCase(arg0);
            return result;
        }
    }
    async listCases(): Promise<Array<CaseView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCases();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCases();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFirs(): Promise<Array<FirRecordView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFirs();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFirs();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFirsFiltered(arg0: FirFilter): Promise<Array<FirRecordView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFirsFiltered(to_candid_FirFilter_n34(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFirsFiltered(to_candid_FirFilter_n34(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSummaries(): Promise<Array<SummaryView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSummaries();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSummaries();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveSummary(arg0: SaveSummaryInput): Promise<SummaryView> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSummary(arg0);
                return from_candid_SummaryView_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSummary(arg0);
            return from_candid_SummaryView_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async triggerFirSummarization(arg0: FirId): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.triggerFirSummarization(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.triggerFirSummarization(arg0);
            return result;
        }
    }
    async updateCase(arg0: UpdateCaseInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCase(to_candid_UpdateCaseInput_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCase(to_candid_UpdateCaseInput_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateFirStatus(arg0: UpdateFirStatusInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFirStatus(to_candid_UpdateFirStatusInput_n43(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFirStatus(to_candid_UpdateFirStatusInput_n43(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateSummary(arg0: UpdateSummaryInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSummary(arg0);
            return result;
        }
    }
}
function from_candid_CaseStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaseStatus): CaseStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_CaseView_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaseView): CaseView {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_FirRecordView_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FirRecordView): Promise<FirRecordView> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_FirStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FirStatus): FirStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_SummaryView_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SummaryView): SummaryView {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CaseId]): CaseId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CaseView]): CaseView | null {
    return value.length === 0 ? null : from_candid_CaseView_n10(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FirRecordView]): Promise<FirRecordView | null> {
    return value.length === 0 ? null : await from_candid_FirRecordView_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SummaryView]): SummaryView | null {
    return value.length === 0 ? null : from_candid_SummaryView_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CaseId;
    status: _CaseStatus;
    title: string;
    caseNumber: string;
    createdBy: _UserId;
    createdDate: _Timestamp;
    firIds: Array<_FirId>;
}): {
    id: CaseId;
    status: CaseStatus;
    title: string;
    caseNumber: string;
    createdBy: UserId;
    createdDate: Timestamp;
    firIds: Array<FirId>;
} {
    return {
        id: value.id,
        status: from_candid_CaseStatus_n12(_uploadFile, _downloadFile, value.status),
        title: value.title,
        caseNumber: value.caseNumber,
        createdBy: value.createdBy,
        createdDate: value.createdDate,
        firIds: value.firIds
    };
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FirId;
    status: _FirStatus;
    offenseType: _OffenseType;
    complainantName: string;
    document: _ExternalBlob;
    caseId: [] | [_CaseId];
    firNumber: string;
    uploadDate: _Timestamp;
    documentFilename: string;
    caseTitle: string;
    uploadedBy: _UserId;
    dateOfIncident: _Timestamp;
}): Promise<{
    id: FirId;
    status: FirStatus;
    offenseType: OffenseType;
    complainantName: string;
    document: ExternalBlob;
    caseId?: CaseId;
    firNumber: string;
    uploadDate: Timestamp;
    documentFilename: string;
    caseTitle: string;
    uploadedBy: UserId;
    dateOfIncident: Timestamp;
}> {
    return {
        id: value.id,
        status: from_candid_FirStatus_n19(_uploadFile, _downloadFile, value.status),
        offenseType: value.offenseType,
        complainantName: value.complainantName,
        document: await from_candid_ExternalBlob_n21(_uploadFile, _downloadFile, value.document),
        caseId: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.caseId)),
        firNumber: value.firNumber,
        uploadDate: value.uploadDate,
        documentFilename: value.documentFilename,
        caseTitle: value.caseTitle,
        uploadedBy: value.uploadedBy,
        dateOfIncident: value.dateOfIncident
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SummaryId;
    firId: _FirId;
    lastEditedDate: [] | [_Timestamp];
    summaryText: string;
    lastEditedBy: [] | [_UserId];
    generatedDate: _Timestamp;
}): {
    id: SummaryId;
    firId: FirId;
    lastEditedDate?: Timestamp;
    summaryText: string;
    lastEditedBy?: UserId;
    generatedDate: Timestamp;
} {
    return {
        id: value.id,
        firId: value.firId,
        lastEditedDate: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.lastEditedDate)),
        summaryText: value.summaryText,
        lastEditedBy: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.lastEditedBy)),
        generatedDate: value.generatedDate
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    open: null;
} | {
    under_investigation: null;
} | {
    chargeshed: null;
}): CaseStatus {
    return "closed" in value ? CaseStatus.closed : "open" in value ? CaseStatus.open : "under_investigation" in value ? CaseStatus.under_investigation : "chargeshed" in value ? CaseStatus.chargeshed : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    summarizing: null;
} | {
    summary_ready: null;
} | {
    summary_failed: null;
} | {
    pending_summary: null;
}): FirStatus {
    return "summarizing" in value ? FirStatus.summarizing : "summary_ready" in value ? FirStatus.summary_ready : "summary_failed" in value ? FirStatus.summary_failed : "pending_summary" in value ? FirStatus.pending_summary : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CaseView>): Array<CaseView> {
    return value.map((x)=>from_candid_CaseView_n10(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FirRecordView>): Promise<Array<FirRecordView>> {
    return await Promise.all(value.map(async (x)=>await from_candid_FirRecordView_n17(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SummaryView>): Array<SummaryView> {
    return value.map((x)=>from_candid_SummaryView_n28(_uploadFile, _downloadFile, x));
}
function to_candid_CaseStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CaseStatus): _CaseStatus {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
async function to_candid_CreateFirInput_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateFirInput): Promise<_CreateFirInput> {
    return await to_candid_record_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FirFilter_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FirFilter): _FirFilter {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_FirStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FirStatus): _FirStatus {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateCaseInput_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateCaseInput): _UpdateCaseInput {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateFirStatusInput_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateFirStatusInput): _UpdateFirStatusInput {
    return to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    offenseType: OffenseType;
    complainantName: string;
    document: ExternalBlob;
    caseId?: CaseId;
    firNumber: string;
    documentFilename: string;
    caseTitle: string;
    dateOfIncident: Timestamp;
}): Promise<{
    offenseType: _OffenseType;
    complainantName: string;
    document: _ExternalBlob;
    caseId: [] | [_CaseId];
    firNumber: string;
    documentFilename: string;
    caseTitle: string;
    dateOfIncident: _Timestamp;
}> {
    return {
        offenseType: value.offenseType,
        complainantName: value.complainantName,
        document: await to_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.document),
        caseId: value.caseId ? candid_some(value.caseId) : candid_none(),
        firNumber: value.firNumber,
        documentFilename: value.documentFilename,
        caseTitle: value.caseTitle,
        dateOfIncident: value.dateOfIncident
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: FirStatus;
    toDate?: Timestamp;
    fromDate?: Timestamp;
    caseId?: CaseId;
}): {
    status: [] | [_FirStatus];
    toDate: [] | [_Timestamp];
    fromDate: [] | [_Timestamp];
    caseId: [] | [_CaseId];
} {
    return {
        status: value.status ? candid_some(to_candid_FirStatus_n36(_uploadFile, _downloadFile, value.status)) : candid_none(),
        toDate: value.toDate ? candid_some(value.toDate) : candid_none(),
        fromDate: value.fromDate ? candid_some(value.fromDate) : candid_none(),
        caseId: value.caseId ? candid_some(value.caseId) : candid_none()
    };
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: CaseId;
    status?: CaseStatus;
    title?: string;
    caseNumber?: string;
}): {
    id: _CaseId;
    status: [] | [_CaseStatus];
    title: [] | [string];
    caseNumber: [] | [string];
} {
    return {
        id: value.id,
        status: value.status ? candid_some(to_candid_CaseStatus_n41(_uploadFile, _downloadFile, value.status)) : candid_none(),
        title: value.title ? candid_some(value.title) : candid_none(),
        caseNumber: value.caseNumber ? candid_some(value.caseNumber) : candid_none()
    };
}
function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: FirId;
    status: FirStatus;
}): {
    id: _FirId;
    status: _FirStatus;
} {
    return {
        id: value.id,
        status: to_candid_FirStatus_n36(_uploadFile, _downloadFile, value.status)
    };
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FirStatus): {
    summarizing: null;
} | {
    summary_ready: null;
} | {
    summary_failed: null;
} | {
    pending_summary: null;
} {
    return value == FirStatus.summarizing ? {
        summarizing: null
    } : value == FirStatus.summary_ready ? {
        summary_ready: null
    } : value == FirStatus.summary_failed ? {
        summary_failed: null
    } : value == FirStatus.pending_summary ? {
        pending_summary: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CaseStatus): {
    closed: null;
} | {
    open: null;
} | {
    under_investigation: null;
} | {
    chargeshed: null;
} {
    return value == CaseStatus.closed ? {
        closed: null
    } : value == CaseStatus.open ? {
        open: null
    } : value == CaseStatus.under_investigation ? {
        under_investigation: null
    } : value == CaseStatus.chargeshed ? {
        chargeshed: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
